//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Xml.Serialization;


namespace AssemblyCSharp
{		
	public enum CharacterClass
	{
		None,
		Warrior,
		Wizard,
		Scorcerer,
		Theif,
		Herbalist,
		Necromancer,
		Paladin,
		Cleric
	}

	[XmlRoot("CharClass")]
	public class CharClass
	{
		[XmlArray("attributeChange")]
		public List<Attribute> attributeChange = new List<Attribute>();

		// list of abillities

		[XmlElement("CharacterClass")]
		public CharacterClass CharacterClass
		{
			get;
			set;
		}

		public CharClass()
		{
		}

		public CharClass (CharacterClass charClass)
		{
			switch (charClass)
			{
				default:
				case CharacterClass.Warrior:
					//statChange.Add(new Stat(StatTypes.Strength, 1));
					//statChange.Add(new Stat(StatTypes.Constitution, 1));
					break;
				case CharacterClass.Wizard:
					//statChange.Add(new Stat(StatTypes.Intelligence, 1));
					break;
				case CharacterClass.Scorcerer:
					break;
				case CharacterClass.Theif:
					break;
				case CharacterClass.Herbalist:
					break;
				case CharacterClass.Necromancer:
					break;
				case CharacterClass.Paladin:
					break;
				case CharacterClass.Cleric:
					break;
			}

		}
	}
}

