//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Xml.Serialization;


namespace AssemblyCSharp
{
	public enum ArmorClasses
	{
		None,
		Light,
		Medium,
		Heavy
	}

	public enum WornPosition
	{
		Head,
		Shoulders,
		Arms,
		Hands,
		Chest,
		Legs,
		Feet,
		Finger
	}

	[XmlRoot("Armour")]
	public class Armour : Item
	{
		[XmlElement("ArmourClass")]
		public ArmorClasses ArmourClass
		{
			get;
			set;
		}

		[XmlElement("WornPosition")]
		public WornPosition WornPosition
		{
			get;
			set;
		}

		public Armour ()
		{
		}
		
		public Armour (ArmorClasses armorClass, WornPosition worn, string name, ItemTypes type, MaterialTypes material, int weight, List<Effect> effects)
			: base(name, type, material, weight, effects)
		{
			ArmourClass = armorClass;
			WornPosition = worn;
		}
	}
}

