//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Xml.Serialization;


namespace AssemblyCSharp
{
	public enum ItemTypes
	{
		Weapon,
		Armour,
		Jewellry
	}

	public enum MaterialTypes
	{
		Cloth,
		Leather,
		Wood,
		Bone,
		Copper,
		Iron,
		Steel
	}


	[XmlRoot("Item")]
	public abstract class Item
	{
		//public List<Stat> statChanges = new List<Stat>();

		// Effects on the item.
		[XmlArray("activeEffects")]
		public List<Effect> activeEffects = new List<Effect>();

		[XmlElement("Name")]
		public string Name
		{
			get;
			set;
		}

		[XmlElement("Type")]
		public ItemTypes Type
		{
			get;
			set;
		}

		[XmlElement("MaterialType")]
		public MaterialTypes MaterialType
		{
			get;
			set;
		}

		// Weight in grams
		[XmlElement("Weight")]
		public int Weight
		{
			get;
			set;
		}

		public Item ()
		{
		}

		//public Item (string name, ItemTypes type, MaterialTypes material, int weight, List<Stat> statChange, List<Effect> effects)
		public Item (string name, ItemTypes type, MaterialTypes material, int weight, List<Effect> effects)
		{
			Name = name;
			Type = type;
			MaterialType = material;
			Weight = weight;
			//statChanges = statChange;
			activeEffects = effects;
		}
	}
}

