//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Xml.Serialization;


namespace AssemblyCSharp
{
	public enum JewellryTypes
	{
		Necklace,
		Ring,
		Brooch,
		Earring,
		Tiara
	}

	[XmlRoot("Jewellry")]
	public class Jewellry : Item
	{
		[XmlElement("JewellryType")]
		public JewellryTypes JewellryType
		{
			get;
			set;
		}

		public Jewellry ()
		{
		}

		public Jewellry (JewellryTypes jewellryType, string name, ItemTypes type, MaterialTypes material, int weight, List<Effect> effects)
			: base(name, type, material, weight, effects)
		{
			JewellryType = jewellryType;
		}
	}
}

