//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Xml.Serialization;


namespace AssemblyCSharp
{
	[XmlRoot("Shield")]
	public class Shield : Item
	{
		[XmlElement("ArmourClass")]
		public ArmorClasses ArmourClass
		{
			get;
			set;
		}

		public Shield ()
		{
		}

		public Shield (ArmorClasses armorClass, string name, ItemTypes type, MaterialTypes material, int weight, List<Effect> effects)
			: base(name, type, material, weight, effects)
		{
		}
	}
}

