//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Xml.Serialization;


namespace AssemblyCSharp
{
	public enum WeaponTypes
	{
		Sword,
		Dagger,
		Staff,
		Mace,
		Hammer,
		Wand,
		Orb,
		Sling,
		Bow
	}

	public enum Range
	{
		Melee,
		Ranged
	}

	public enum Handedness
	{
		Single,
		Two
	}

	public enum DamageTypes
	{
		Slashing,
		Peircing,
		Bludgening,
		Magic
	}


	[XmlRoot("Weapon")]
	public class Weapon : Item
	{
		[XmlElement("DamageAmount")]
		public int DamageAmount
		{
			get;
			 set;
		}

		[XmlElement("WeaponType")]
		public WeaponTypes WeaponType
		{
			get;
			set;
		}

		[XmlElement("Handed")]
		public Handedness Handed
		{
			get;
			set;
		}

		[XmlElement("DamageType")]
		public DamageTypes DamageType
		{
			get;
			set;
		}

		public Weapon ()
		{
		}

		public Weapon (int damage, WeaponTypes weaponType, Handedness handed, DamageTypes damageType, string name, ItemTypes type, MaterialTypes material, int weight, List<Effect> effects)
			: base(name, type, material, weight, effects)
		{
			DamageAmount = damage;
			WeaponType = weaponType;
			Handed = handed;
			DamageType = damageType;
		}
	}
}

